# Generated by Django 5.0 on 2025-11-24 23:45

import django.db.models.deletion
import pgvector.django
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agents', '0002_initial'),
        ('projects', '0001_initial'),
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodeArtifact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file_path', models.CharField(db_index=True, max_length=500)),
                ('file_name', models.CharField(max_length=255)),
                ('language', models.CharField(blank=True, max_length=50)),
                ('content', models.TextField()),
                ('content_hash', models.CharField(db_index=True, max_length=64)),
                ('line_count', models.IntegerField(default=0)),
                ('embedding', pgvector.django.VectorField(blank=True, dimensions=1536, null=True)),
                ('structure', models.JSONField(blank=True, default=dict)),
                ('last_modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_files', to='agents.agentinstance')),
                ('last_modified_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tasks.task')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='code_artifacts', to='projects.project')),
            ],
            options={
                'verbose_name': 'Code Artifact',
                'verbose_name_plural': 'Code Artifacts',
                'db_table': 'code_artifacts',
            },
        ),
        migrations.CreateModel(
            name='CodeChange',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('change_type', models.CharField(choices=[('created', 'Created'), ('modified', 'Modified'), ('deleted', 'Deleted'), ('renamed', 'Renamed')], db_index=True, max_length=20)),
                ('content_before', models.TextField(blank=True)),
                ('content_after', models.TextField()),
                ('diff', models.TextField(blank=True)),
                ('reason', models.TextField(blank=True)),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='agents.agentinstance')),
                ('artifact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='changes', to='code.codeartifact')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tasks.task')),
            ],
            options={
                'verbose_name': 'Code Change',
                'verbose_name_plural': 'Code Changes',
                'db_table': 'code_changes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ArtifactRegistry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('artifact_type', models.CharField(db_index=True, max_length=50)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('file_path', models.CharField(max_length=500)),
                ('line_start', models.IntegerField(blank=True, null=True)),
                ('line_end', models.IntegerField(blank=True, null=True)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('dependencies', models.JSONField(blank=True, default=list)),
                ('embedding', pgvector.django.VectorField(blank=True, dimensions=1536, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_by_agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='agents.agentinstance')),
                ('created_by_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tasks.task')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artifact_registry', to='projects.project')),
            ],
            options={
                'verbose_name': 'Artifact Registry',
                'verbose_name_plural': 'Artifact Registries',
                'db_table': 'artifact_registry',
                'indexes': [models.Index(fields=['project', 'artifact_type'], name='artifact_re_project_1c22e9_idx'), models.Index(fields=['name'], name='artifact_re_name_61c80f_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='codeartifact',
            index=models.Index(fields=['project', 'file_path'], name='code_artifa_project_1f25df_idx'),
        ),
        migrations.AddIndex(
            model_name='codeartifact',
            index=models.Index(fields=['language'], name='code_artifa_languag_4d2d81_idx'),
        ),
        migrations.AddIndex(
            model_name='codeartifact',
            index=models.Index(fields=['content_hash'], name='code_artifa_content_df0120_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='codeartifact',
            unique_together={('project', 'file_path')},
        ),
        migrations.AddIndex(
            model_name='codechange',
            index=models.Index(fields=['artifact', 'created_at'], name='code_change_artifac_38b423_idx'),
        ),
    ]
