# Generated by Django 5.0 on 2025-11-24 23:45

import django.db.models.deletion
import pgvector.django
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agents', '0002_initial'),
        ('projects', '0001_initial'),
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Decision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('decision_type', models.CharField(db_index=True, max_length=100)),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField()),
                ('reasoning', models.TextField()),
                ('alternatives', models.JSONField(blank=True, default=list)),
                ('affected_components', models.JSONField(blank=True, default=list)),
                ('embedding', pgvector.django.VectorField(blank=True, dimensions=1536, null=True)),
                ('status', models.CharField(choices=[('proposed', 'Proposed'), ('approved', 'Approved'), ('implemented', 'Implemented'), ('superseded', 'Superseded')], db_index=True, default='approved', max_length=20)),
                ('made_by_agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='agents.agentinstance')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decisions', to='projects.project')),
                ('related_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tasks.task')),
                ('superseded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='context.decision')),
            ],
            options={
                'verbose_name': 'Decision',
                'verbose_name_plural': 'Decisions',
                'db_table': 'decisions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['project', 'status'], name='decisions_project_3b0304_idx'), models.Index(fields=['decision_type'], name='decisions_decisio_d5f0cf_idx')],
            },
        ),
        migrations.CreateModel(
            name='EventLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_type', models.CharField(db_index=True, max_length=100)),
                ('event_data', models.JSONField()),
                ('actor_type', models.CharField(max_length=20)),
                ('actor_id', models.CharField(blank=True, max_length=100)),
                ('sequence_number', models.BigIntegerField(db_index=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='projects.project')),
            ],
            options={
                'verbose_name': 'Event Log',
                'verbose_name_plural': 'Event Logs',
                'db_table': 'event_log',
                'ordering': ['sequence_number'],
                'indexes': [models.Index(fields=['project', 'sequence_number'], name='event_log_project_e1fb00_idx'), models.Index(fields=['event_type'], name='event_log_event_t_cb4184_idx'), models.Index(fields=['created_at'], name='event_log_created_f1efd5_idx')],
            },
        ),
        migrations.CreateModel(
            name='Memory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('memory_type', models.CharField(choices=[('requirement', 'Requirement'), ('decision', 'Decision'), ('architecture', 'Architecture'), ('code_pattern', 'Code Pattern'), ('error_resolution', 'Error Resolution'), ('conversation', 'Conversation'), ('learning', 'Learning')], db_index=True, max_length=20)),
                ('title', models.CharField(max_length=500)),
                ('content', models.TextField()),
                ('embedding', pgvector.django.VectorField(dimensions=1536)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('importance', models.FloatField(default=0.5)),
                ('access_count', models.IntegerField(default=0)),
                ('created_by_agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='agents.agentinstance')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memories', to='projects.project')),
                ('related_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tasks.task')),
            ],
            options={
                'verbose_name': 'Memory',
                'verbose_name_plural': 'Memories',
                'db_table': 'memories',
                'indexes': [models.Index(fields=['project', 'memory_type'], name='memories_project_678093_idx'), models.Index(fields=['importance'], name='memories_importa_d97495_idx')],
            },
        ),
    ]
