# Generated by Django 5.0 on 2025-11-24 23:45

import django.contrib.postgres.fields
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentInstance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('idle', 'Idle'), ('working', 'Working'), ('waiting_input', 'Waiting for Input'), ('waiting_dependency', 'Waiting for Dependency'), ('blocked', 'Blocked'), ('error', 'Error'), ('completed', 'Completed')], db_index=True, default='idle', max_length=20)),
                ('status_message', models.TextField(blank=True)),
                ('custom_instructions', models.TextField(blank=True)),
                ('model_override', models.CharField(blank=True, max_length=50)),
                ('temperature_override', models.FloatField(blank=True, null=True)),
                ('working_memory', models.JSONField(blank=True, default=dict)),
                ('conversation_history', models.JSONField(blank=True, default=list)),
                ('tasks_completed', models.IntegerField(default=0)),
                ('errors_encountered', models.IntegerField(default=0)),
                ('total_tokens_used', models.IntegerField(default=0)),
                ('last_active_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Agent Instance',
                'verbose_name_plural': 'Agent Instances',
                'db_table': 'agent_instances',
            },
        ),
        migrations.CreateModel(
            name='AgentMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('message_type', models.CharField(choices=[('task_assignment', 'Task Assignment'), ('question', 'Question'), ('answer', 'Answer'), ('status_update', 'Status Update'), ('review_request', 'Review Request'), ('review_feedback', 'Review Feedback'), ('blocker', 'Blocker'), ('decision', 'Decision'), ('handoff', 'Handoff'), ('user_input', 'User Input')], db_index=True, max_length=20)),
                ('content', models.JSONField()),
                ('context_refs', models.JSONField(blank=True, default=list)),
                ('requires_response', models.BooleanField(default=False)),
                ('responded', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Agent Message',
                'verbose_name_plural': 'Agent Messages',
                'db_table': 'agent_messages',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='AgentType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=100, unique=True)),
                ('role', models.CharField(db_index=True, max_length=50, unique=True)),
                ('description', models.TextField()),
                ('system_prompt', models.TextField()),
                ('available_tools', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=list, size=None)),
                ('can_hire', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=list, size=None)),
                ('hierarchy_level', models.IntegerField(choices=[(0, 'Orchestrator'), (1, 'Architect'), (2, 'Lead'), (3, 'Senior'), (4, 'Junior')], default=3)),
                ('default_model', models.CharField(default='deepseek-r1:7b', max_length=50)),
                ('default_temperature', models.FloatField(default=0.7)),
                ('max_iterations', models.IntegerField(default=50)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'verbose_name': 'Agent Type',
                'verbose_name_plural': 'Agent Types',
                'db_table': 'agent_types',
                'ordering': ['hierarchy_level', 'name'],
            },
        ),
        migrations.CreateModel(
            name='AgentAction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action_type', models.CharField(db_index=True, max_length=50)),
                ('action_data', models.JSONField()),
                ('is_reversible', models.BooleanField(default=True)),
                ('reverse_action', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(default='completed', max_length=20)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_actions', to='projects.project')),
            ],
            options={
                'verbose_name': 'Agent Action',
                'verbose_name_plural': 'Agent Actions',
                'db_table': 'agent_actions',
                'ordering': ['created_at'],
            },
        ),
    ]
