# Generated by Django 4.2.11 on 2025-11-30 20:02

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('backend', 'Backend Developer'), ('frontend', 'Frontend Developer'), ('devops', 'DevOps Engineer'), ('fullstack', 'Full Stack Developer'), ('designer', 'UI/UX Designer')], max_length=50)),
                ('system_prompt', models.TextField()),
                ('capabilities', models.JSONField(default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'agents_agent',
            },
        ),
        migrations.CreateModel(
            name='AgentAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_assignments', to='agents.agent')),
            ],
            options={
                'db_table': 'agents_agentassignment',
            },
        ),
    ]
