# Generated by Django 4.2.11 on 2025-11-30 20:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        ('agents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentassignment',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_assignments', to='projects.project'),
        ),
        migrations.AddConstraint(
            model_name='agentassignment',
            constraint=models.UniqueConstraint(fields=('project', 'agent'), name='unique_project_agent'),
        ),
    ]
