# Generated by Django 5.0 on 2025-11-24 23:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agents', '0001_initial'),
        ('projects', '0001_initial'),
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentaction',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actions', to='tasks.task'),
        ),
        migrations.AddField(
            model_name='agentinstance',
            name='current_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_agents', to='tasks.task'),
        ),
        migrations.AddField(
            model_name='agentinstance',
            name='hired_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hired_agents', to='agents.agentinstance'),
        ),
        migrations.AddField(
            model_name='agentinstance',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agents', to='projects.project'),
        ),
        migrations.AddField(
            model_name='agentaction',
            name='agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='agents.agentinstance'),
        ),
        migrations.AddField(
            model_name='agentmessage',
            name='from_agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to='agents.agentinstance'),
        ),
        migrations.AddField(
            model_name='agentmessage',
            name='parent_message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='agents.agentmessage'),
        ),
        migrations.AddField(
            model_name='agentmessage',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_messages', to='projects.project'),
        ),
        migrations.AddField(
            model_name='agentmessage',
            name='to_agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to='agents.agentinstance'),
        ),
        migrations.AddField(
            model_name='agentinstance',
            name='agent_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='instances', to='agents.agenttype'),
        ),
        migrations.AddIndex(
            model_name='agentaction',
            index=models.Index(fields=['project', 'created_at'], name='agent_actio_project_18c195_idx'),
        ),
        migrations.AddIndex(
            model_name='agentaction',
            index=models.Index(fields=['agent'], name='agent_actio_agent_i_73a990_idx'),
        ),
        migrations.AddIndex(
            model_name='agentaction',
            index=models.Index(fields=['action_type'], name='agent_actio_action__c59ed0_idx'),
        ),
        migrations.AddIndex(
            model_name='agentmessage',
            index=models.Index(fields=['project', 'created_at'], name='agent_messa_project_160196_idx'),
        ),
        migrations.AddIndex(
            model_name='agentmessage',
            index=models.Index(fields=['from_agent'], name='agent_messa_from_ag_205fc1_idx'),
        ),
        migrations.AddIndex(
            model_name='agentmessage',
            index=models.Index(fields=['to_agent'], name='agent_messa_to_agen_cc0d9c_idx'),
        ),
        migrations.AddIndex(
            model_name='agentmessage',
            index=models.Index(fields=['message_type'], name='agent_messa_message_a5ab15_idx'),
        ),
        migrations.AddIndex(
            model_name='agentinstance',
            index=models.Index(fields=['project', 'status'], name='agent_insta_project_3e80d0_idx'),
        ),
        migrations.AddIndex(
            model_name='agentinstance',
            index=models.Index(fields=['agent_type'], name='agent_insta_agent_t_2899ee_idx'),
        ),
        migrations.AddIndex(
            model_name='agentinstance',
            index=models.Index(fields=['last_active_at'], name='agent_insta_last_ac_7fed92_idx'),
        ),
    ]
