# Generated by Django 5.0 on 2025-11-30 19:07

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Plan",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                (
                    "plan_type",
                    models.CharField(
                        choices=[
                            ("free", "Free"),
                            ("pro", "Pro"),
                            ("team", "Team"),
                            ("enterprise", "Enterprise"),
                        ],
                        max_length=20,
                        unique=True,
                    ),
                ),
                ("price_monthly", models.DecimalField(decimal_places=2, max_digits=10)),
                ("price_yearly", models.DecimalField(decimal_places=2, max_digits=10)),
                ("messages_per_window", models.IntegerField(default=10)),
                ("max_conversations", models.IntegerField(default=5)),
                ("context_window", models.IntegerField(default=4096)),
                ("max_active_projects", models.IntegerField(default=1)),
                ("max_archived_projects", models.IntegerField(default=0)),
                ("max_files_per_project", models.IntegerField(default=10)),
                ("project_requests_per_window", models.IntegerField(default=2)),
                ("available_agents", models.JSONField(default=list)),
                ("max_concurrent_agents", models.IntegerField(default=1)),
                ("storage_limit_mb", models.IntegerField(default=10)),
                ("max_file_size_kb", models.IntegerField(default=100)),
                ("retention_days", models.IntegerField(default=7)),
                ("model_tier", models.CharField(default="basic", max_length=20)),
                ("max_output_tokens", models.IntegerField(default=1024)),
                ("requests_per_minute", models.IntegerField(default=2)),
                ("max_concurrent_connections", models.IntegerField(default=1)),
                ("queue_priority", models.IntegerField(default=0)),
                ("has_thinking_mode", models.BooleanField(default=False)),
                ("has_download", models.BooleanField(default=False)),
                ("has_git_integration", models.BooleanField(default=False)),
                ("has_api_access", models.BooleanField(default=False)),
                ("has_chat_search", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "billing_plan",
            },
        ),
        migrations.CreateModel(
            name="Subscription",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("cancelled", "Cancelled"),
                            ("expired", "Expired"),
                            ("past_due", "Past Due"),
                            ("trialing", "Trialing"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                (
                    "billing_cycle",
                    models.CharField(
                        choices=[("monthly", "Monthly"), ("yearly", "Yearly")],
                        default="monthly",
                        max_length=20,
                    ),
                ),
                (
                    "stripe_subscription_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "stripe_customer_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("current_period_start", models.DateTimeField()),
                ("current_period_end", models.DateTimeField()),
                ("trial_end", models.DateTimeField(blank=True, null=True)),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="billing.plan"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscription",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "billing_subscription",
            },
        ),
        migrations.CreateModel(
            name="UsageLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "usage_type",
                    models.CharField(
                        choices=[
                            ("chat_message", "Chat Message"),
                            ("project_request", "Project Request"),
                            ("file_created", "File Created"),
                            ("file_updated", "File Updated"),
                            ("download", "Project Download"),
                        ],
                        max_length=30,
                    ),
                ),
                ("conversation_id", models.UUIDField(blank=True, null=True)),
                ("project_id", models.UUIDField(blank=True, null=True)),
                ("input_tokens", models.IntegerField(default=0)),
                ("output_tokens", models.IntegerField(default=0)),
                (
                    "estimated_cost",
                    models.DecimalField(decimal_places=6, default=0, max_digits=10),
                ),
                ("model_used", models.CharField(blank=True, max_length=100)),
                ("duration_ms", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="usage_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "billing_usage_log",
                "indexes": [
                    models.Index(
                        fields=["user", "created_at"],
                        name="billing_usa_user_id_0bf585_idx",
                    ),
                    models.Index(
                        fields=["usage_type", "created_at"],
                        name="billing_usa_usage_t_539e7d_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="UsageTracker",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("window_start", models.DateTimeField()),
                ("window_end", models.DateTimeField()),
                ("chat_messages_used", models.IntegerField(default=0)),
                ("chat_tokens_used", models.IntegerField(default=0)),
                ("project_requests_used", models.IntegerField(default=0)),
                ("project_tokens_used", models.IntegerField(default=0)),
                ("storage_used_bytes", models.BigIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="usage_records",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "billing_usage_tracker",
                "indexes": [
                    models.Index(
                        fields=["user", "window_start"],
                        name="billing_usa_user_id_9b4d24_idx",
                    ),
                    models.Index(
                        fields=["window_end"], name="billing_usa_window__7153ee_idx"
                    ),
                ],
                "unique_together": {("user", "window_start")},
            },
        ),
    ]
