"""Project models."""

import uuid
from django.db import models
from django.conf import settings


class Project(models.Model):
    """Project model for AI-generated code projects."""

    PROJECT_TYPES = [
        ('fullstack', 'Full Stack'),
        ('backend', 'Backend Only'),
        ('frontend', 'Frontend Only'),
        ('api', 'API Only'),
        ('mobile', 'Mobile App'),
    ]

    STATUS_CHOICES = [
        ('created', 'Created'),
        ('in_progress', 'In Progress'),
        ('completed', 'Completed'),
        ('archived', 'Archived'),
    ]

    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name='projects'
    )
    name = models.CharField(max_length=255)
    description = models.TextField(blank=True)
    project_type = models.CharField(max_length=50, choices=PROJECT_TYPES, default='fullstack')
    status = models.CharField(max_length=20, choices=STATUS_CHOICES, default='created')
    settings = models.JSONField(default=dict, blank=True)  # Project-specific settings
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        db_table = 'projects_project'
        ordering = ['-updated_at']
        indexes = [
            models.Index(fields=['user', '-created_at']),
            models.Index(fields=['user', 'status']),
        ]

    def __str__(self):
        return f"{self.name} ({self.user.email})"

    def get_file_tree(self):
        """Get project file tree structure."""
        files = self.files.all().order_by('path')
        tree = {}
        for file in files:
            parts = file.path.split('/')
            current = tree
            for i, part in enumerate(parts):
                if i == len(parts) - 1:
                    current[part] = {'type': 'file', 'id': str(file.id)}
                else:
                    if part not in current:
                        current[part] = {'type': 'directory', 'children': {}}
                    current = current[part]['children']
        return tree


class ProjectFile(models.Model):
    """Files generated by AI for a project."""

    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    project = models.ForeignKey(
        Project,
        on_delete=models.CASCADE,
        related_name='files'
    )
    path = models.CharField(max_length=500)  # e.g., "backend/models.py"
    content = models.TextField()
    language = models.CharField(max_length=50, blank=True)  # python, typescript, etc.
    version = models.IntegerField(default=1)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        db_table = 'projects_projectfile'
        ordering = ['path']
        constraints = [
            models.UniqueConstraint(
                fields=['project', 'path'],
                name='unique_project_file_path'
            )
        ]

    def __str__(self):
        return f"{self.project.name}/{self.path}"

    def save(self, *args, **kwargs):
        # Auto-detect language from file extension
        if not self.language:
            ext_map = {
                '.py': 'python',
                '.ts': 'typescript',
                '.tsx': 'typescript',
                '.js': 'javascript',
                '.jsx': 'javascript',
                '.html': 'html',
                '.css': 'css',
                '.json': 'json',
                '.yml': 'yaml',
                '.yaml': 'yaml',
                '.md': 'markdown',
                '.sql': 'sql',
                '.sh': 'bash',
                '.dockerfile': 'dockerfile',
            }
            ext = '.' + self.path.split('.')[-1].lower() if '.' in self.path else ''
            self.language = ext_map.get(ext, 'text')
        super().save(*args, **kwargs)
